### ISSUE TITLE
header

### ISSUE THREAD

**Issue by sookyoungwoo** [ts-beginner/Info.gg#2]
### ✨ Describe

헤더를 개발한다.

### ✅ Tasks

- [ ] 로고 사진 넣기
- [ ] 헤더 목록 만들기
- [ ] 목록 hover시 목록 만들기
